FROM jolielang/jolie-docker-deployer
MAINTAINER Claudio Guidi <guidiclaudio@gmail.com>
COPY public public
COPY busStopRetriever.ol main.ol
COPY config.ini config.ini
COPY locations.iol locations.iol
EXPOSE 9005
