FROM jolielang/jolie-docker-deployer
MAINTAINER Claudio Guidi <guidiclaudio@gmail.com>
COPY lib lib
COPY public public
COPY core_queries.iol core_queries.iol
COPY gtfs_core.ol main.ol
COPY locations.iol locations.iol
EXPOSE 9000
EXPOSE 9001
