FROM jolielang/jolie-docker-deployer
MAINTAINER Claudio Guidi <guidiclaudio@gmail.com>
COPY META-INF META-INF
COPY public public
COPY www www
COPY config.iol config.iol
COPY frontend.ol frontend.ol
COPY leonardo.ol main.ol
COPY locations.iol locations.iol
EXPOSE 8001
EXPOSE 8002
