FROM jolielang/jolie-docker-deployer
MAINTAINER Claudio Guidi <guidiclaudio@gmail.com>
COPY public public
COPY busEta.ol main.ol
COPY helloBusWrapper.ol helloBusWrapper.ol
COPY locations.iol locations.iol
EXPOSE 9006
